name: 'Cleanup Terraform PR Comments and Labels'
description: 'Delete no-changes comments and labels for a specific Terraform environment'

inputs:
  environment:
    description: 'Environment name (dev or prod)'
    required: true
  prNumber:
    description: 'Pull request number'
    required: true
  githubToken:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Delete no-changes comments
      env:
        GH_TOKEN: ${{ inputs.githubToken }}
      shell: bash
      run: |
        # Delete comments containing "No changes" for this environment
        echo "Looking for comments containing 'No changes' and '${{ inputs.environment }}/'"

        # Debug: Show all comment bodies that contain "No changes"
        echo "All comments with 'No changes':"
        gh pr view ${{ inputs.prNumber }} --json comments --jq '.comments[] | select(.body | contains("No changes")) | {id: .databaseId, bodyPreview: .body[0:200]}'

        # Get matching comment IDs
        COMMENT_IDS=$(gh pr view ${{ inputs.prNumber }} --json comments --jq '.comments[] | select(.body | contains("No changes") and contains("${{ inputs.environment }}/")) | .databaseId')

        if [ -z "$COMMENT_IDS" ]; then
          echo "No matching comments found to delete"
        else
          echo "Found comment IDs to delete:"
          echo "$COMMENT_IDS"

          # Delete each comment
          echo "$COMMENT_IDS" | while read -r comment_id; do
            if [ -n "$comment_id" ]; then
              echo "Deleting comment ID: $comment_id"
              gh api -X DELETE /repos/${{ github.repository }}/issues/comments/$comment_id || echo "Failed to delete comment $comment_id"
            fi
          done
        fi

    - name: Remove no-changes labels
      env:
        GH_TOKEN: ${{ inputs.githubToken }}
      shell: bash
      run: |
        # Remove labels with /no-changes suffix for this environment
        gh pr view ${{ inputs.prNumber }} --json labels --jq '.labels[].name' | \
          grep "^${{ inputs.environment }}/.*no-changes$" | \
          xargs -I {} gh pr edit ${{ inputs.prNumber }} --remove-label "{}" || true
