name: 'Cleanup Terraform PR Comments and Labels'
description: 'Delete no-changes comments and labels for a specific Terraform environment'

inputs:
  environment:
    description: 'Environment name (dev or prod)'
    required: true
  prNumber:
    description: 'Pull request number'
    required: true
  githubToken:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Delete no-changes comments
      env:
        GH_TOKEN: ${{ inputs.githubToken }}
      shell: bash
      run: |
        # Delete comments containing "No changes" for this environment
        echo "Looking for comments containing 'No changes' and '${{ inputs.environment }}/'"

        # Debug: Show available fields in comments
        echo "Debug: Available fields in first comment:"
        gh pr view ${{ inputs.prNumber }} --json comments --jq '.comments[0] | keys'

        # Debug: Show all comment info
        echo "All comments with 'No changes':"
        gh pr view ${{ inputs.prNumber }} --json comments --jq '.comments[] | select(.body | contains("No changes")) | {id: .id, url: .url, bodyPreview: .body[0:150]}'

        # Get comment URLs for deletion (using REST API endpoint from comment URL)
        echo "Attempting to delete comments..."
        gh pr view ${{ inputs.prNumber }} --json comments --jq -r '.comments[] | select(.body | contains("No changes") and contains("${{ inputs.environment }}/")) | .url' | \
          while read -r comment_url; do
            if [ -n "$comment_url" ]; then
              echo "Deleting comment: $comment_url"
              gh api -X DELETE "$comment_url" || echo "Failed to delete comment at $comment_url"
            fi
          done

    - name: Remove no-changes labels
      env:
        GH_TOKEN: ${{ inputs.githubToken }}
      shell: bash
      run: |
        # Remove labels with /no-changes suffix for this environment
        gh pr view ${{ inputs.prNumber }} --json labels --jq '.labels[].name' | \
          grep "^${{ inputs.environment }}/.*no-changes$" | \
          xargs -I {} gh pr edit ${{ inputs.prNumber }} --remove-label "{}" || true
