---
name: Terraform Apply

description: Terraform Apply

inputs:
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true
  gcp-workload-identity-provider:
    description: GCP Workload Identity Provider (domain ディレクトリの場合に必要)
    required: false
  gcp-service-account:
    description: GCP Service Account (domain ディレクトリの場合に必要)
    required: false

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud (for domain directory)
      if: inputs.gcp-workload-identity-provider != '' && inputs.gcp-service-account != ''
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.gcp-workload-identity-provider }}
        service_account: ${{ inputs.gcp-service-account }}

    - name: Set contact_address_lines as JSON
      if: env.CONTACT_ADDRESS_LINES != ''
      run: |
        echo "TF_VAR_contact_address_lines=$(echo "$CONTACT_ADDRESS_LINES" | jq -R -c 'split(",")')" >> $GITHUB_ENV
      shell: bash

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        # domain ディレクトリで使用される変数を TF_VAR_ で渡す
        TF_VAR_gcp_project_id: ${{ env.GCP_PROJECT_ID }}
        TF_VAR_cloudflare_api_token: ${{ env.CLOUDFLARE_API_TOKEN }}
        TF_VAR_cloudflare_account_id: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
        TF_VAR_contact_country_code: ${{ env.CONTACT_COUNTRY_CODE }}
        TF_VAR_contact_postal_code: ${{ env.CONTACT_POSTAL_CODE }}
        TF_VAR_contact_administrative_area: ${{ env.CONTACT_ADMINISTRATIVE_AREA }}
        TF_VAR_contact_locality: ${{ env.CONTACT_LOCALITY }}
        TF_VAR_contact_recipient: ${{ env.CONTACT_RECIPIENT }}
        TF_VAR_contact_email: ${{ env.CONTACT_EMAIL }}
        TF_VAR_contact_phone: ${{ env.CONTACT_PHONE }}
        TF_VAR_yearly_price_currency: ${{ env.YEARLY_PRICE_CURRENCY }}
        TF_VAR_yearly_price_units: ${{ env.YEARLY_PRICE_UNITS }}
