name: '🚀 Feature Request'
description: Propose new features or improvements for EduQuest.
labels: [enhancement]
title: '[Feature] '
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Desired Experience
        Share your idea and the value it would bring to users.
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Summarize the feature or improvement in one sentence.
      placeholder: 'Example: Progress summary card showing completion rate per stage'
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: User Story
      description: 'Describe "who, why, and what" in the format: "As a [user type], I want [goal] because [reason]."'
      placeholder: "Example: As a parent of an elementary student, I want to see my child's learning progress at a glance because I want to support their review sessions."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Detailed Idea
      description: Provide specifics like screen mockups, scenarios, or required data. Diagrams and links are welcome.
      placeholder: 'Example: Display a progress ring and recent achievement list on the dashboard'
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Expected Priority
      options:
        - 🟥 ASAP (Needed for next release)
        - 🟧 High (1-2 sprints)
        - 🟨 Medium (When timing allows)
        - 🟩 Low (Sharing an idea)
      description: Add context in notes if needed.
    validations:
      required: true
  - type: textarea
    id: metrics
    attributes:
      label: Success Metrics
      description: How will we measure success? What user feedback should we look for?
      placeholder: 'Example: Stage completion rate increases by 10%, positive parent survey feedback'
  - type: textarea
    id: related
    attributes:
      label: Related Information
      description: Reference links, existing issues, or research materials.
      placeholder: 'Example: #256 (Learning history API), Figma mockup: https://...'
  - type: checkboxes
    id: collaboration
    attributes:
      label: Collaboration Interests
      description: Let us know if you can help with implementation or testing.
      options:
        - label: Can participate in specification and requirements definition
        - label: Can perform design review
        - label: Can contribute to implementation (code)
        - label: Can help with user testing
