name: D1 Migrations (prod)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  apply-prod:
    name: Apply migrations to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Apply migrations
        uses: ./.github/actions/d1-migrations
        with:
          environment: prod
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Slack Notification (failure)
        if: failure()
        uses: ./.github/actions/slack-deploy-failure
        with:
          environment: prod
          slackWebhook: ${{ secrets.SLACK_WEBHOOK_PROD }}
          workflowName: ${{ github.workflow }}
          jobName: ${{ github.job }}
          runUrl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
