name: D1 Migrations (dev)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply-dev:
    name: Apply migrations to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Apply migrations
        uses: ./.github/actions/d1-migrations
        with:
          environment: dev
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
