name: Deploy to Production

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy to production environment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy to Cloudflare Workers
        uses: ./.github/actions/wrangler-deploy
        with:
          environment: prod
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          resendApiKey: ${{ secrets.RESEND_API_KEY_PROD }}

      - name: Slack Notification (failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: '#edu-quest-prod'
          SLACK_COLOR: danger
          SLACK_TITLE: 'Deploy to Production failed'
          SLACK_MESSAGE: |
            本番環境へのデプロイが失敗しました。ログを確認して対応をお願いします。
            workflow: ${{ github.workflow }}
            job: ${{ github.job }}
            run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_LINK_NAMES: 'true'
          SLACK_USERNAME: github-bot
          SLACK_ICON_EMOJI: ':x:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PROD }}
