---
name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      # pre-commit の terraform-fmt 用
      - uses: jdx/mise-action@v2
        with:
          version: 2025.9.13
          cache: true

      - run: mise install

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: -a --show-diff-on-failure
