---
name: prek

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prek:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # prek の terraform-fmt 用
      - uses: jdx/mise-action@v3
        with:
          version: 2025.9.13
          cache: true

      - run: mise install

      # Install prek
      - name: Install prek
        run: |
          brew install prek

      # Run prek on all files
      - name: Run prek
        run: |
          prek run --all-files --show-diff-on-failure
